name = "Not a UHC Pack"
author = "Luna"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d5309c937721e7eaf6a0ec890ab2f1eb7aaea60b96dc8071f5eb5a8ec8a4036"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
