name = "Not a UHC Pack"
author = "Luna"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8a63a1fa7e7afad8c2738752ecffb34c8dc1852ef308c9c8a3a451234564bb2"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"
